motion-android-app/config/routes.rb
Rails.application.routes.draw do
  resources :motion_data
  resources :configs
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

motion-android-app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

motion-android-app/app/models/config.rb
class Config < ApplicationRecord
end

motion-android-app/app/models/motion_datum.rb
class MotionDatum < ApplicationRecord
end

motion-android-app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

motion-android-app/app/controllers/configs_controller.rb
class ConfigsController < ApplicationController
  before_action :set_config, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token

  # GET /configs
  # GET /configs.json
  def index
    @configs = Config.all
  end

  # GET /configs/1
  # GET /configs/1.json
  def show
  end

  # GET /configs/new
  def new
    @config = Config.new
  end

  # GET /configs/1/edit
  def edit
  end

  # POST /configs
  # POST /configs.json
  def create
    @config = Config.new(config_params)

    #normaly it would be placed in rails env's
    hmac_secret = 'my$ecretK3y'

    exp = Time.now.to_i + 5 * 3600
    exp_payload = { exp: exp }

    token = JWT.encode exp_payload, hmac_secret, 'HS256'
    #byebug

    @config.token = token

    respond_to do |format|
      if @config.save
        format.json { render :show, status: :created, location: @config }
      else
        format.html { render :new }
        format.json { render json: @config.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /configs/1
  # PATCH/PUT /configs/1.json
  def update
    respond_to do |format|
      if @config.update(config_params)
        format.html { redirect_to @config, notice: 'Config was successfully updated.' }
        format.json { render :show, status: :ok, location: @config }
      else
        format.html { render :edit }
        format.json { render json: @config.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /configs/1
  # DELETE /configs/1.json
  def destroy
    @config.destroy
    respond_to do |format|
      format.html { redirect_to configs_url, notice: 'Config was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_config
      @config = Config.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def config_params
      params.permit(:positionIntervalInMinutes, :trackedObjectId)
    end
end

motion-android-app/app/controllers/motion_data_controller.rb
class MotionDataController < ApplicationController
  before_action :set_motion_datum, only: [:show, :edit, :update, :destroy]
  skip_before_action :verify_authenticity_token

  # GET /motion_data
  # GET /motion_data.json
  def index
    @motion_data = MotionDatum.all
  end

  # GET /motion_data/1
  # GET /motion_data/1.json
  def show
  end

  # GET /motion_data/new
  def new
    @motion_datum = MotionDatum.new
  end

  # GET /motion_data/1/edit
  def edit
  end

  # POST /motion_data
  # POST /motion_data.json
  def create
    @motion_datum = MotionDatum.new(motion_datum_params)
    hmac_secret = 'my$ecretK3y'

    token = request.headers["Authorization"]
    token = token.split(" ")[1]
    #byebug
    begin
      decoded_token = JWT.decode token, hmac_secret, true, { algorithm: 'HS256' }
      respond_to do |format|
        if @motion_datum.save
          format.html { redirect_to @motion_datum, notice: 'Motion datum was successfully created.' }
          format.json { render :show, status: :created, location: @motion_datum }
        else
          format.html { render :new }
          format.json { render json: @motion_datum.errors, status: :unprocessable_entity }
        end
      end

    rescue JWT::ExpiredSignature
      puts "Token expired"
    end
  end

  # PATCH/PUT /motion_data/1
  # PATCH/PUT /motion_data/1.json
  def update
    respond_to do |format|
      if @motion_datum.update(motion_datum_params)
        format.html { redirect_to @motion_datum, notice: 'Motion datum was successfully updated.' }
        format.json { render :show, status: :ok, location: @motion_datum }
      else
        format.html { render :edit }
        format.json { render json: @motion_datum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /motion_data/1
  # DELETE /motion_data/1.json
  def destroy
    @motion_datum.destroy
    respond_to do |format|
      format.html { redirect_to motion_data_url, notice: 'Motion datum was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_motion_datum
      @motion_datum = MotionDatum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def motion_datum_params
      params.permit(:accuracy, :altitude, :longitude, :timestamp, :trackedObjectId, :latitude)
    end
end

motion-android-app/app/helpers/application_helper.rb
module ApplicationHelper
end

motion-android-app/app/helpers/configs_helper.rb
module ConfigsHelper
end

motion-android-app/app/helpers/motion_data_helper.rb
module MotionDataHelper
end

motion-android-app/app/views/configs/_form.html.erb
<%= form_with(model: config, local: true) do |form| %>
  <% if config.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(config.errors.count, "error") %> prohibited this config from being saved:</h2>

      <ul>
        <% config.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :positionIntervalInMinutes %>
    <%= form.text_field :positionIntervalInMinutes %>
  </div>

  <div class="field">
    <%= form.label :token %>
    <%= form.text_field :token %>
  </div>

  <div class="field">
    <%= form.label :trackedObjectId %>
    <%= form.text_field :trackedObjectId %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

motion-android-app/app/views/configs/edit.html.erb
<h1>Editing Config</h1>

<%= render 'form', config: @config %>

<%= link_to 'Show', @config %> |
<%= link_to 'Back', configs_path %>

motion-android-app/app/views/configs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Configs</h1>

<table>
  <thead>
    <tr>
      <th>Positionintervalinminutes</th>
      <th>Token</th>
      <th>Trackedobjectid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @configs.each do |config| %>
      <tr>
        <td><%= config.positionIntervalInMinutes %></td>
        <td><%= config.token %></td>
        <td><%= config.trackedObjectId %></td>
        <td><%= link_to 'Show', config %></td>
        <td><%= link_to 'Edit', edit_config_path(config) %></td>
        <td><%= link_to 'Destroy', config, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Config', new_config_path %>

motion-android-app/app/views/configs/new.html.erb
<h1>New Config</h1>

<%= render 'form', config: @config %>

<%= link_to 'Back', configs_path %>

motion-android-app/app/views/configs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Positionintervalinminutes:</strong>
  <%= @config.positionIntervalInMinutes %>
</p>

<p>
  <strong>Token:</strong>
  <%= @config.token %>
</p>

<p>
  <strong>Trackedobjectid:</strong>
  <%= @config.trackedObjectId %>
</p>

<%= link_to 'Edit', edit_config_path(@config) %> |
<%= link_to 'Back', configs_path %>

motion-android-app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MotionAndroidApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

motion-android-app/app/views/motion_data/_form.html.erb
<%= form_with(model: motion_datum, local: true) do |form| %>
  <% if motion_datum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(motion_datum.errors.count, "error") %> prohibited this motion_datum from being saved:</h2>

      <ul>
        <% motion_datum.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :accuracy %>
    <%= form.text_field :accuracy %>
  </div>

  <div class="field">
    <%= form.label :altitude %>
    <%= form.text_field :altitude %>
  </div>

  <div class="field">
    <%= form.label :longitude %>
    <%= form.text_field :longitude %>
  </div>

  <div class="field">
    <%= form.label :timestamp %>
    <%= form.text_field :timestamp %>
  </div>

  <div class="field">
    <%= form.label :trackedObjectId %>
    <%= form.text_field :trackedObjectId %>
  </div>

  <div class="field">
    <%= form.label :latitude %>
    <%= form.text_field :latitude %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

motion-android-app/app/views/motion_data/edit.html.erb
<h1>Editing Motion Datum</h1>

<%= render 'form', motion_datum: @motion_datum %>

<%= link_to 'Show', @motion_datum %> |
<%= link_to 'Back', motion_data_path %>

motion-android-app/app/views/motion_data/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Motion Data</h1>

<table>
  <thead>
    <tr>
      <th>Accuracy</th>
      <th>Altitude</th>
      <th>Longitude</th>
      <th>Timestamp</th>
      <th>Trackedobjectid</th>
      <th>Latitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @motion_data.each do |motion_datum| %>
      <tr>
        <td><%= motion_datum.accuracy %></td>
        <td><%= motion_datum.altitude %></td>
        <td><%= motion_datum.longitude %></td>
        <td><%= motion_datum.timestamp %></td>
        <td><%= motion_datum.trackedObjectId %></td>
        <td><%= motion_datum.latitude %></td>
        <td><%= link_to 'Show', motion_datum %></td>
        <td><%= link_to 'Edit', edit_motion_datum_path(motion_datum) %></td>
        <td><%= link_to 'Destroy', motion_datum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Motion Datum', new_motion_datum_path %>

motion-android-app/app/views/motion_data/new.html.erb
<h1>New Motion Datum</h1>

<%= render 'form', motion_datum: @motion_datum %>

<%= link_to 'Back', motion_data_path %>

motion-android-app/app/views/motion_data/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Accuracy:</strong>
  <%= @motion_datum.accuracy %>
</p>

<p>
  <strong>Altitude:</strong>
  <%= @motion_datum.altitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @motion_datum.longitude %>
</p>

<p>
  <strong>Timestamp:</strong>
  <%= @motion_datum.timestamp %>
</p>

<p>
  <strong>Trackedobjectid:</strong>
  <%= @motion_datum.trackedObjectId %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @motion_datum.latitude %>
</p>

<%= link_to 'Edit', edit_motion_datum_path(@motion_datum) %> |
<%= link_to 'Back', motion_data_path %>